### PR TITLE
Add help text for `clear_datastore` command

### PR DESCRIPTION
**Pull request by JVickery-TBS**
Added `clear_datastore` command and logic action. This action will never drop the table in the datastore, it will only delete rows of data. Updated the Recombinant API Help tab.

### CODE REVIEW

**Comment by wardi** [comment]
`datastore_delete` being used for both deleting records and the whole table is a ckan footgun that has existed for a very long time. I think that's what you're trying to work around with this change so why don't we discuss a proper fix upstream instead?

**Comment by JVickery-TBS** [comment]
@wardi Yeah, we did not know if this was really a troublesome thing in Core, as the documentation for it was pretty clear on how it is used.

I can easily add the `datastore_clear` command to Core. I can throw in a PR sometime today/tomorrow morning for the contribution.

**Comment by wardi** [comment]
@JVickery-TBS `clear` to me says "remove all records" maybe there's a better name.. "datastore_records_delete" maybe? I'm sure it will be discussed on the PR.

**Comment by wardi** [comment]
For the other part of this change I'm not sure how useful the `clear_datastore` command is. When re-importing records all the required resources/datastore tables will be created automatically so deleting them should be fine, and it's a little weird to have a command that deletes all records with specific reference numbers while ignoring the owning organization.

In the past I've used the `show` command to give me the resource ids for particular orgs and then used `ckanapi action datastore_delete resource_id=... filter:...` for this kind of thing

**Comment by JVickery-TBS** [comment]
@wardi I just added in the `paster` command to have the same behavior as the action. Just in the case that we needed to do any system stuff with the command. But if we do not need it, we can chuck it.

**Comment by JVickery-TBS** [comment]
I will have the action name be `datastore_records_delete` in the contrib to core PR.

**Pull request closed without merging**
