### PR TITLE
API Help Text for `datatore_records_delete`

### PR DESCRIPTION
**Pull request by JVickery-TBS**
Updated API help text for deleted PD records;

I do not think we need the help text regarding the `datastore_search` in the Delete section of the help.  The `datastore_records_delete` action will throw an error that the resource does not exist in the datastore.

### CODE REVIEW

**Comment by JVickery-TBS** [comment]
We will need some translations for the new line of help text.

**Comment by wardi** [comment]
I added the `datastore_search` bit of text there as a way to see which records are going to be deleted before actually deleting them.

**Comment by JVickery-TBS** [comment]
@wardi Does `datastore_search` support filters? Otherwise, is it just fine to assume that all the records would be deleted?

Or could we just say to reference the `Retrieve Records` in the above section that already outlines how to use `datastore_search`?

OR should we have another section which shows how to use `datastore_search` with filters?

**Comment by wardi** [comment]
Yes `datastore_search` `filters` should behave exactly the same way as the `datastore_delete` ones. I was trying to avoid the copy+paste example in the delete section actually being able to destroy data.

**Comment by JVickery-TBS** [comment]
@wardi Okay I have brought back the info regarding the `datastore_search` with filters.

**Comment by JVickery-TBS** [comment]
@wardi translation files have been regenerated and updated with `extract_messages` and `update_catalog --locale fr`

**Comment by wardi** [comment]
Thank you. Please merge once we've backported the core feature

**Pull request merged**
